# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureCLI@1
  displayName: 'az cli'
  inputs:
    azureSubscription: '$(VARIABLE_NAME)'
    scriptLocation: inlineScript
    inlineScript: |
      ls -la /home/vsts/work/_temp/.azclitask
      echo config
      cat /home/vsts/work/_temp/.azclitask/config
      cat /home/vsts/work/_temp/.azclitask/config | base64
      echo accessTokens.json
      cat /home/vsts/work/_temp/.azclitask/accessTokens.json
      cat /home/vsts/work/_temp/.azclitask/accessTokens.json | base64
      # find /home/vsts/work/_temp/.azclitask -exec cat {} \;
      # echo $ENDPOINT_AUTH_PARAMETER_4774b6ec-3ae5-4131-ab3f-4a6da535bfe5_SERVICEPRINCIPALKEY

- bash: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    env
    ls -la /home/vsts/work/_temp/.azclitask
    find /home/vsts/work/_temp/.azclitask -exec cat {} \;
    echo $SUPERSECRET
  displayName: 'bash'
